services:
  backend:
    build: ./backend2
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - FLASK_APP=run.py

  frontend:
    build: ./frontend/frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend


  trigger:
    build: ./Trigger
    depends_on:
      - backend

networks:
  default:
    external:
      name: my-shared-network
  
volumes:
  frontend_node_modules:
